module.exports = {
  EventType: {
    PLAYER_INIT: 'PLAYER_INIT',
    NEW_OPONENT: 'NEW_OPONENT',
    TXT_MESSAGE: 'TXT_MESSAGE',
    GAME_CLEAR: 'GAME_CLEAR',
    GAME_MOVES: 'GAME_MOVES',
    USER_LEAVE: 'USER_LEAVE',
    REMOVE_OPONENT: 'REMOVE_OPONENT',
    USER_SURREND: 'USER_SURREND',
    USER_WIN: 'USER_WIN',
    LINE_CONFIRMED: 'LINE_CONFIRMED',
    CLEAR_MOVES: 'CLEAR_MOVES'
  }
}